### PR TITLE
🚚 Move methods to lamindb

### PR DESCRIPTION
**Pull request by falexwolf**
- https://github.com/laminlabs/lamindb/pull/770

### CODE REVIEW

**Comment by Koncopd** [comment]
Hm, `delete` is a part of basic functionality for a model, not sure it is the right decision to move it out.

**Comment by falexwolf** [comment]
But didn't you just agree to it 2 days ago? https://laminlabs.slack.com/archives/C047606PR2R/p1686660094826889?thread_ts=1686659123.978819&cid=C047606PR2R

**Comment by falexwolf** [comment]
It makes things a lot simpler (both DRY & testing) even just for storage: https://github.com/laminlabs/lamindb/pull/770

**Comment by falexwolf** [comment]
Of course, all other methods would also be moved, including __init__ etc.

**Comment by Koncopd** [comment]
Yep, but i thought that only non-essential methods would be moved. But i agree, that this is fine if everything is moved.

**Comment by falexwolf** [comment]
Ohh, got it! Then that was a misunderstanding! I was really thinking of _all_ methods, because also the "essential" ones contain logic that needs to be properly tested.

(And additionally, where would we draw the line between what is an essential and a non-essential method. We'd need to discuss this all the time... if we can have one clear policy, then that's easier [assuming the policy checks out])

**Comment by Koncopd** [comment]
Maybe just a few comments also needed that most functionality for some models is defined in `lamindb`.

**Comment by falexwolf** [comment]
Yes, will do!

But it will be very clear with the re-organization of files in lamindb. Literally all logic is going to be in lamindb in locations that make sense, and none here in lnschema-core.

**Pull request merged**
